### ISSUE TITLE
Establish a basic code proposal -> review -> test -> approval -> merge -> deploy workflow

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#128]
## Acceptance Criteria
- [ ] Documenting code and design review, in docs
- [ ] Documenting the QASP and merging into Docs (tracking in #217)
- [ ] Tests we want to install
- [ ] Code to cloud
- [ ] Update README with contributing instructions

This includes CI/CD, but is more than just that. Who reviews? What constitutes approval? Who merges? Small but important things.

**Comment by colinmurphy01** [comment]
@greg-does-weather I believe this is what we'd want to setup in the next sprint?

**Comment by greg-does-weather** [comment]
The engineering goal for the next sprint would enable this. I think it's reasonable to include this issue in next sprint, but it may not be completed. Part of what needs to happen is agreement about some stuff, and it may not make sense to talk about that until we've got more of the pieces and parts in place. But if we're far enough along, we could use coworking time in the second week to make a pitch!

**Comment by greg-does-weather** [comment]
Also draft a proposal for standards around things like branching strategy, merging strategy (merge-squash, merge rebase, regular merge, or squash before merging), etc.
