### ISSUE TITLE
e2.v1 styles, header, footer

### ISSUE THREAD

**Issue by janelx** [weather-gov/weather.gov#161]
🎨 [Link in figma](https://www.figma.com/file/0dSABt9zCqoknaKua6DHmP/NOAA---Weather.gov?type=design&node-id=345-2102&mode=design)

### Supported user stories
… I want to know this is an official NWS and gov website (2.2)

### Design (define/discovery)
- [x] Done - part of layout and visual exploration #111 

### Support needed
- USWDS & NOAA style guide - Banner, Footer ([example of approved implementation on NOS](https://oceanservice.noaa.gov/))
- CMS:  footer links
- Editor - who can update these links?
- [x] #189
- [ ] Build menus and forms to capture site-wide info (logos, site title, site alt, etc)
- [x] Build responsive base template with regions for banner, alerts, footer menus, etc.

### Permissions and roles
- [ ]  Need definition

### Acceptance criteria
_Not included in this story (will be a separate story): navigation, alerts, site search)_

**User story**
- [ ] As a member of the public I can quickly identify and trust that weather.gov is an official website of the federal gov't and the official website for NWS

**General:**
- [ ] Responsive
- [ ] USWDS friendly
- [ ] Section 508 compliant
- [ ] Translation friendly

#### Styles:
- [ ] Based on USWDS - default to USWDS unless setting mentioned below:
  - [ ] Font-family: "Nunito Sans","Open Sans","Helvetica Neue",sans-serif
  - [ ] Brand colors: 
    - [ ] sky blue = #003087 (color-primary)
    - [ ] water blue = #0085CA (color-primary-light)
    - [ ] white =  #fff
    - [ ] dark gray = #333
- [ ] Body links: color = #003087 (color-primary)

#### Header:
![image](https://github.com/18F/weather.gov/assets/93934808/18d97d5e-4a7c-4e3e-a418-b22e32a9f622)
*The header follows NOAA style guidelines and based on [USWDS header component](https://designsystem.digital.gov/components/header/). Note: NOAA has a guideline for displaying alerts but will be part of the alert ticket.*

- [ ] Shows on every page
- [ ] Correct NOAA logo link to github [svg](https://github.com/18F/weather.gov/blob/main/docs/designs/e2v1-styles-header-footer%20/noaa-logo-rgb-2022.svg)) 
  - [ ] Links to weather.gov
  - [ ] Alt text should be “National Oceanic and Atmospheric Administration logo” and coded as a link 
  - [ ] Clear space, the area around the logo that should be free from text or other design elements, is 0.25 of the height of the logo. [example](https://drive.google.com/file/d/1N5AdJaF40lp2SnwOrLFw-ohur-ym8p6d/view?pli=1)
  - [ ] Same logo for favicon
- [ ] Align the header logo/site name block so this element is justified with the left edge of the body content. 
- [ ] Site title: "National Weather Service"
  - [ ] Links to weather.gov
- [ ] Subtitle "National Oceanic and Atmospheric Administration"
  - [ ] Links to noaa.gov

#### Banner:
![image](https://github.com/18F/weather.gov/assets/93934808/1d89462c-c2d6-40e2-af8f-78f3752d1d90)
 - [ ] Implementation of USWDS banner component. See [U.S. Web Design System (USWDS) for banner definition and specifications](https://designsystem.digital.gov/components/banner/)
 - [ ] [Drupal: NOAA Drupal installation documentation](https://docs.google.com/document/d/1cxAK2YiaM7yvD2658Kjr2ipsBTZE38okLS_JmPwgkO0/edit?pli=1#heading=h.u4sibpg966iy) - May need to log into NOAA account to view

#### Footer
![image](https://github.com/18F/weather.gov/assets/93934808/ceda41ab-c7f5-4075-897c-031d5880f9d8)

*The footer follows NOAA style guidelines and based off of [USWDS footer component](https://designsystem.digital.gov/components/footer/)*
- [ ] NOAA logo with tagline and click on NOAA logo to navigate to noaa.gov
   - [ ] Alt text should be “National Oceanic and Atmospheric Administration logo” and coded as a link 
- [ ] Links are displayed in two columns on tablet (USWDS default) or greater. View design for order of links.
- [ ] Links in this section are underlined (see design or NOS)
- [ ] Following links are clickable and navigate to (required):
  - [ ] “About” page: specific to your site. *(use placeholder - need to add to site)*
  - [ ] Privacy policy: specific to your site. *(use placeholder - need to add to site)*
  - [ ] Accessibility: specific to your site. *(use placeholder - need to add to site)*
  - [ ] Disclaimer: specific to your site. *(use placeholder - need to add to site)*
  - [ ] Information Quality: May link to NOAA.gov page: https://www.noaa.gov/organization/information-technology/policy-oversight/information-quality
  - [ ] FOIA: May link to NOAA.gov page: https://www.noaa.gov/information-technology/foia
  - [ ] USA.gov: Link to USA.gov.
- [ ] Additional links
  - [ ] Media inquiries: UPDATED: goes to https://www.noaa.gov/NOAA-Communications
  - [ ] Site Index: A HTML page that lists all website pages *(use placeholder - need to add to site)*
  - [ ] USA.gov: This provides a link to the U.S. government’s “top-level” website and also reinforces that your site is part of the larger U.S. federal government family.

#### Agency Identification links
![image](https://github.com/18F/weather.gov/assets/93934808/62e9fe76-f4c4-42f7-ad21-fdb5b7f09913)
- [ ] Orgs are in descending order from left to right (see design)
- [ ] Following links are clickable and navigate to (required):
  - [ ] Department of Commerce: https://www.commerce.gov/ 
  - [ ] National Oceanic and Atmospheric Administration (NOAA). Acronym NOAA in parentheses at the end to help build association with this acronym - https://www.noaa.gov/
  - [ ] National weather service: https//www.weather.gov

### CMS
... I would like to be to quickly and confidently be able to update the footer section to add links, remove and/or edit links as defined and needed by NOAA style guide
  - [ ] Able to update, remove, and add a links to footer based on permission settings (which role will have this permission is TBD)
  - [ ] Suggested instructions: Footer links for NOAA websites. Any changes to footers links will be reflected site wide for weather.gov. These links should should be updated to match NOAA Style and Design guide > Footer. Please reference the style guide before making updates. 

```[tasklist]
### Review: design, function and flow:
- [ ] POs - org alignment and vision review
- [x] Eng - feasibility review
- [ ] UX - what and how to test
```

```[tasklist]
### Story details
- [ ] Reviewed designs (must be attached)
- [x] Acceptance criteria define (added to this story)
```

**Comment by janelx** [comment]
@colinmurphy01 @cannandev  I've documented the acceptance criteria. Please let me know if you'd prefer the acceptance criteria in a separate doc instead of being entered into here. 

It's ready for PO review. Some items to pull out for some extra attention:
Header:
- Optional: display parent agency: "National Atmos..."
Footer:
  - Links: correctly linked (placeholder)
  - Additional links: which ones to keep
Need to add content
  - About
  - Privacy policy
  - Accessibility

Note:
Who and how are links update? Are additional links needed?
@kmranjo is defining this

**Comment by colinmurphy01** [comment]
This is REALLY great work.

Did a quick PO review, will confirm with NWS POs
- Looked up guidance on alt text for logos, updated acceptance criteria for Header and Footer
- Suggested that site map link is placeholder for now, unless creating the additional HTML page now is easy and worth the time

**Comment by janelx** [comment]
@colinmurphy01 @cannandev per Colin's question above, I added "Translation friendly" under the overall  acceptance criteria. I'm not sure how if translation is implement sitewide, by page or component but I do know there are translations of USWDS banner component. Feel free to move it if doesn't make sense there. 

@colinmurphy01 yes site title and sub title should link to the corresponding entities. Good catch. I've updated the the above

I also added some suggested instructions (help text) for CMS view of footer links: _"Footer links for NOAA websites. Any changes to footers links will be reflected site wide for weather.gov. These links should should be updated to match NOAA Style and Design guide > Footer. Please reference the style guide before making updates."_ I didn't add the link b/c I'm not sure if it'll ever change (currently on internal Google Site). We can add it but risk it needing to be updated and another level of management for small amount of impact?

**Comment by janelx** [comment]
**Possible new stories:**
These are items that don't have a home right now and not represented in our Main MVP user stories:
- Site wide search (this is a requirement and good practice)
- Site navigation
- Who and how are links updated? Are additional links needed? I've currently captured this under CMS as the user story below. 
> ... I would like to be to quickly and confidently be able to update the footer section to add links, remove and/or edit links as defined and needed by NOAA style guide

**Comment by colinmurphy01** [comment]
Yea good call.

Our primary methods for MVP were search by location, but yea site-wide search for content is a question mark. I'll add it to a story board and we can discuss.

**Comment by janelx** [comment]
To do from our story refinement this morning: create 3/4 different variations of the header
- NWS logo. Site title: National Weather Service. Subtitle: NOAA
  - NWS logo without the text (maybe with red lines)
- NWS logo. Site title: Weather.gov Subtitle: National Weather Service
- NWS logo. Site title: Weather.gov Subtitle: [slogan] Weather ready nation

**Comment by cannandev** [comment]
> Our primary methods for MVP were search by location, but yea site-wide search for content is a question mark. I'll add it to a story board and we can discuss.

Speaking of search, the current site uses search.gov, not an internal search. Just a few things to consider: Do we want to continue using search.gov? What are the risks/consequences of not using it? Should search results be limited to MVP pages or include current weather.gov pages too?

**Comment by cannandev** [comment]
@janelx Is there a responsive design for the footer? I'm assuming columns should be collapsed into one column on mobile, then three on tablet?

**Comment by colinmurphy01** [comment]
What's the status for reviewing this after dev?

Does this need Design and PO review?

**Comment by claire-skies-noaa** [comment]
@janelx @colinmurphy01 I'm still blocked deploying this to https://weather.app.cloud.gov/. But we're so close! You can try pulling this locally using [these](https://github.com/weather-gov/weather.gov/pull/279) deployment instructions.

Once you can see the site, I'd like to review/demo with the following in mind:

### Nunito Sans font
There are [6 different variations](https://fonts.google.com/specimen/Nunito+Sans) of this font, none of which match exactly what you've got in the design :grimace: – which one are you using? I'm using `Regular 400`.

### Header

- Mobile text sizes header - made one size smaller
- Site name `lg`
- Slogan `2xs`
- Breakpoint `desktop`

### Primary footer links

- I'll center the footer logo in a future commit. Please ignore for now.
- Will the motto ever be translated? Should it be content managed like the header site slogan?
- Items meant to be read top to bottom, correct? 
- This is one list, not two. I'm creating columns with CSS instead of manually adding additional regions. If we add another link, if will go to the end of the list in the second column. We can rearrange them in the UI.
- We probably need a separate ticket to address external links? How do we want to handle them universally? I suggest [using the external icon](https://designsystem.digital.gov/components/link/#component-preview) and the default browser behavior -- opening target page in the same window.

### Agency footer links
- I'll add pipes between the agency links in a future commit. Please ignore for now.

**Comment by colinmurphy01** [comment]
Discussed in eng/design

- Use an icon to indicate any external website
- Use default brower behavior
- We are not grouping links in footer, move forward with 1 list
