### ISSUE TITLE
Milestone Planning

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#223]
Accpetance Criteria

- [x] We have identified the work we'd like to focus on through the rest of the calendar year
- [x] We've documented it in the phase / sprint plan
- [x] The core team is informed of everyone's priorities

**Comment by colinmurphy01** [comment]
Used mural to facilitate conversation
Documenting Epics and Work in [roadmap view](https://github.com/orgs/weather-gov/projects/2/views/8)

**Comment by colinmurphy01** [comment]
last thing I need to do is document all of the work in the roadmap view of our github board

**Comment by colinmurphy01** [comment]
To-dos
- [ ] Github reflects the work from milestone planning
- [ ] We have a document for how we manage our work, visibility into that, and milestone expecations

**Comment by colinmurphy01** [comment]
Shared in Champions meeting

**Comment by kmranjo** [comment]
Added components in that column on the roadmap where possible, but more conversation within the team is needed since some aren't defined fully enough for it to be confirmed that they could meet that need.
