### ISSUE TITLE
NWS share-out materials

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#245]
## Channels
- Ken’s 10 page - update
- Proactive Push - Newsletter
  - MVP + Development Environment is live
  - Onsite in Nashville and research

## To-Dos
- [ ] - [ ] Kari to provide guide
- [ ] Colin to write draft for Weather.gov MVP
- [ ] Shad and Kari to review/edit
- [ ] Share with team for thoughts
- [ ] send to Corey?

**Comment by colinmurphy01** [comment]
@shadkeene can you link our ken's10 page?

**Comment by shadkeene** [comment]
https://sites.google.com/noaa.gov/nws-insider/news-updates/kens-10
