### ISSUE TITLE
Create sample procurement milestone schedule to share with NWS

### ISSUE THREAD

**Issue by burnsbrian** [weather-gov/weather.gov#263]
Create milestones for procurement so NWS can see timeline / plan accordingly

- [ ] Set up meeting with NWS to determine chosen path forward (hire vendor or not)
- [ ] What date would we need to award a contract if hiring a vendor
- [ ] Draft a milestone schedule based on meeting with NWS
- [ ] Meet with NWS to present milestones
- [ ] Revise milestones if needed

**Comment by colinmurphy01** [comment]
we can call this done for now #285
