### ISSUE TITLE
FISMA / ATO Strategy Options and Decision

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#35]
### Background
ACIO is giving is a lot of flexibility to define the best security and compliance strategy for our system. The system is currently FISMA High. 

### Acceptance Criteria
- [ ] FISMA level for Weather.gov 2.0
- [ ] Approach to ATO, which components we will inherit vs. create new
- [ ] Alignment and commitment to a security and compliance strategy from the ISSO and ACIO
- [ ] We are able to evaluate components of our architecture
- [ ] We are able to start defining our controls

### Tasks
- [x] Meet with the WOC to get set up
- [x] Meet with ACIO and ISSO to decide 
- [ ] #14
- [ ] #41 
- [ ] #6
- [ ] Align and Decide

**Comment by colinmurphy01** [comment]
Supporting doc drafted by @cannandev https://docs.google.com/document/d/1-BR6AHTFD-HCXsNcwOWf7-dZyrwA4Lz9G4hCY0B7So4/edit#heading=h.7cgvyr8ta3q
