### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#361]
### Background
Question came in from Corey/comms.  I'm assuming this is a no, but curious if anyone's considered.  Is an internal URL-shortener considered with [weather.gov](http://weather.gov/) 2.0?  One of the reasons would be that external URL shorteners lose trust (not gov domain) and they are used a good bit in NWS.  I'm guessing this is out of scope...but just wanted to confirm.

### Tasks
- [ ] Research to understand the need and scope of impact
- [ ] Research to understand feasibility with engineering
- [ ] Document and prioritize in Now/Next/Later
