### ISSUE TITLE
Explore legacy conditions labels and use of `shortForecast` text

### ISSUE THREAD

**Issue by eric-gade** [weather-gov/weather.gov#451]
### Description
We currently maintain a "l[egacy mapping](https://github.com/weather-gov/weather.gov/blob/main/web/modules/weather_data/src/Service/legacyMapping.json)" for icon paths to our canonical set of icons. These also include a select set of short conditions descriptions.  
  
Both the completed Hourly Forecast and in-progress Daily Forecast blocks have been using these conditions as the text for the blocks. However, they are not very detailed and often hide important information when compared to the text from the `shortForecast` field from the API.
  
Take the following comparison of values from a daily forecast request for Brooklyn:
```json
[
  {
    "legacyCondition": "Snow",
    "shortForecast": "Slight Chance Snow Showers",
    "day": "This Afternoon"
  },
  {
    "legacyCondition": "A few clouds and windy",
    "shortForecast": "Mostly Clear",
    "day": "Tonight"
  },
  {
    "legacyCondition": "Partly cloudy",
    "shortForecast": "Mostly Sunny",
    "day": "Wednesday"
  },
  {
    "legacyCondition": "Partly cloudy",
    "shortForecast": "Partly Cloudy",
    "day": "Wednesday Night"
  },
  {
    "legacyCondition": "A few clouds",
    "shortForecast": "Sunny",
    "day": "Thursday"
  },
  {
    "legacyCondition": "Partly cloudy",
    "shortForecast": "Partly Cloudy",
    "day": "Thursday Night"
  },
  {
    "legacyCondition": "Mostly cloudy",
    "shortForecast": "Mostly Cloudy then Light Rain",
    "day": "Friday"
  },
  {
    "legacyCondition": "Rain",
    "shortForecast": "Light Rain",
    "day": "Friday Night"
  },
  {
    "legacyCondition": "Mostly cloudy",
    "shortForecast": "Partly Sunny",
    "day": "Saturday"
  },
  {
    "legacyCondition": "Mostly cloudy",
    "shortForecast": "Mostly Cloudy then Slight Chance Light Rain",
    "day": "Saturday Night"
  },
  {
    "legacyCondition": "Rain",
    "shortForecast": "Chance Light Rain",
    "day": "Sunday"
  },
  {
    "legacyCondition": "Rain",
    "shortForecast": "Chance Light Rain",
    "day": "Sunday Night"
  },
  {
    "legacyCondition": "Rain",
    "shortForecast": "Chance Light Rain",
    "day": "Monday"
  },
  {
    "legacyCondition": "Rain",
    "shortForecast": "Chance Light Rain",
    "day": "Monday Night"
  }
]
```
  
### Tasks
- [ ] Find any documents / records about how the initial "conditions" labels ("description" in the corresponding source spreadsheet) were decided upon
- [ ] Determine whether or not we want a canonical set of condition descriptions as in the mapping, or whether we simply want to use the `shortForecast` text from the API
- [ ] If we do want to use the API values, update the Hourly and Daily Forecast blocks to use the `shortForecast` text.

**Comment by colinmurphy01** [comment]
I believe this work was tracked in #455 and #472? @eric-gade can you confirm and close?

**Comment by colinmurphy01** [comment]
I'm gonna close, feel free to reopen.
