### ISSUE TITLE
I know what hazards are occurring for a specific location and able to interpret its severity (at-a-glance)

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#68]
### Description
We know coming out of PA the ability to know when something hazardous is coming and what impact it can have on their day is key information from the site, from the public and EMS. We know this is also the most unique value of weather.gov in the market of weather apps/channels because everyone points to NWS.

**Related Boulder: #57 **

### Considerations for discovery

- Identify the common data points and information needed, irregardless of the hazard
- Should we break out short-fuse vs. long-fuse into 2 unique use cases
- 3 letter codes that indicate the type of hazard (TDR - thunderstorm, SVW - severe, FFD - flash flood), the data doesnt look different it's just that encoding
- Limitations in real-time hazards for Nashville, but we could look across the country for inspiration

### Acceptance criteria

- [x] Documenting the bare minimum content types for "at a glance" across hazards
- [x] Document any unique or detailed content types for weather (not comprehensive)
- [x] Synthesize recommendations to ideal use case 
- [x] Recommendations for content types that should be included in hazards 
- [x] Examples of hazard text
- [x] Update design considerations

### [Research document available here](https://docs.google.com/document/d/1hd_GaXtlW-YZk3L57J3eWCb5fHBNmOw9uFPnDZPMjSg/edit?usp=sharing)
Completed research includes information on: 
- What NWS hazard products are and how they are generated
- Which elements of current processes and tools are flexible, and which are not
- How other sites communicate hazards (majority of this research completed in [competitive analysis](https://docs.google.com/presentation/d/1Xct6T6VMP9KoL-iJRM0d96jslojUyCuqbUuJBe4S_18/edit?usp=sharing))
- Best practices around crisis communication according to recent academic research  

### Main takeaways 
- Bring information around active hazards for a specific location onto the page directly so that the most vital information is front and center. 
- Update language around hazards to be plain, simple, specific, and actionable.
- Test the inclusion of maps and/or graphics alongside hazard messaging to determine the extent to which it adds value (for both location page and hazard page). 
- Ensure safety actions that users are being prompted to take are comprehensive and consistent across locations and distribution channels. 
- Provide space for more detailed, specific guidance to be easily available to users when they need it. 
- Create a space to share hazard-specific, location-agnostic information so that users are better able to share it and EMs are better able to use it  (secondary to MVP?) 

### Next Steps ([captured in detail in document](https://docs.google.com/document/d/1hd_GaXtlW-YZk3L57J3eWCb5fHBNmOw9uFPnDZPMjSg/edit?usp=sharing)) 
- Set up time to discuss risk assessment as a team and align on a recommended approach to bring to partners 
- Review & prioritize recommended design items
   - Hazard detail component 
   - New language around hazards 
   - Dedicated hazard page (possibly not MVP?) 
   - Hazard maps (possibly not MVP?) 
   - Safety content section (dependent on research)
- Review & prioritize recommended research 
   - Discovery around systems involved in hazard generation to get a detailed understanding of the risks involved in updates to each one
   - Discovery around auto-generated hazard language and its inconsistencies 
   - Discovery/comprehensive review of safety content (national and local) 

-----------

### Design considerations
**For prototype:** I know if there is currently a thunderstorm alert (watch, advisory, warning) for Nashville, TN, severity, duration, impact and suggested actions

- Present on page only when hazards are active for that area 
- When present, is the primary content on page 
- Includes the following content:
   - What is the hazard
   - What is its impact
   - When is it expected to arrive / leave 
   - What do I need to do to stay safe 
   - Where can I get more information about the hazard
   - Where can I get more information about safety actions that apply specifically to my circumstances 

### Out of Scope
- Location of storm on a map
- Forecast discussion
- Safety information
- Actual text for alerts (for entire project)

### User research (to test later)
- What are optimal formats for getting this info (text, visuals, color, etc)?

### OOS
- AQI and other sever weather-related hazards
- Focusing on understanding sever weather and impact, not taking action (separate)

```[tasklist]
### Tasks
- [ ] https://github.com/18F/weather.gov/issues/111
```

**Comment by kmranjo** [comment]
@colinmurphy01  Completed research and recommendations, but would like to discuss how to move forward since this ticket has shifted a few times. Not sure what to do with the tasks here.

**Comment by colinmurphy01** [comment]
I believe we are done with this work as we move forward with exploring and designing hazard components. There is still discovery and design that needs to happen at the component level and we can track that individually. Confirm @janelx @kmranjo

**Comment by janelx** [comment]
@colinmurphy01 yes this complete. @kmranjo feel free to close if you also feel it's complete/captured in MVP backlog
