### ISSUE TITLE
As a member of the public, I can find weather information for a specific location.

### ISSUE THREAD

**Issue by colinmurphy01** [weather-gov/weather.gov#97]
### Description
It is currently very difficult to find relevant information on weather.gov and one of the main reasons why people either don't use the site or struggle to use it for their job. 

Blocked by #99 

**Outcome: Easier to find**

### Justification
- Value: High
- Viability: High
- Alignment: Medium

```[tasklist]
### Stories for consideration
- [ ] I can search the site with a zip code or city to find my weather information
- [ ] I want the site to know my location automatically
- [ ] I shouldn’t need to re-search my location every time
- [ ] I know where to find more information that is relevant to me in preparing and/or navigating a hazard
```

**Comment by colinmurphy01** [comment]
Closing Epic tickets and rethinking how we want to communicate our roadmap.
